/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 11-nov.-2023 15:31:04 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS Car CASCADE
;

DROP TABLE IF EXISTS Car_Situtuion CASCADE
;

DROP TABLE IF EXISTS Change_Type CASCADE
;

DROP TABLE IF EXISTS Date CASCADE
;

DROP TABLE IF EXISTS Driver CASCADE
;

DROP TABLE IF EXISTS Driver_Situacion CASCADE
;

DROP TABLE IF EXISTS "Group" CASCADE
;

DROP TABLE IF EXISTS Mod_Change CASCADE
;

DROP TABLE IF EXISTS Modification CASCADE
;

DROP TABLE IF EXISTS Programming_Type CASCADE
;

DROP TABLE IF EXISTS Route CASCADE
;

DROP TABLE IF EXISTS Solicitude CASCADE
;

DROP TABLE IF EXISTS Type_Car_Situation CASCADE
;

DROP TABLE IF EXISTS Type_Driver_Situation CASCADE
;

/* Create Tables */

CREATE TABLE Car
(
	car_number varchar(7) NOT NULL,
	car_brand varchar(50) NOT NULL,
	number_of_seats integer NOT NULL,
	cs_code integer NULL
)
;

CREATE TABLE Car_Situtuion
(
	cs_code integer NOT NULL,
	return_date_cs date NOT NULL,
	current_date_cs date NOT NULL,
	id_type_sitc integer NULL
)
;

CREATE TABLE Change_Type
(
	id_change_type integer NOT NULL,
	change_type_name varchar(50) NOT NULL,
	id_mod_change integer NULL
)
;

CREATE TABLE Date
(
	id_date date NOT NULL,
	hour time without time zone NOT NULL
)
;

CREATE TABLE Driver
(
	dni varchar(11) NOT NULL,
	driver_name varchar(50) NOT NULL,
	home_address varchar(50) NOT NULL,
	category varchar(30) NOT NULL,
	is_copilot boolean NOT NULL,
	car_number varchar(7) NOT NULL,
	ds_code integer NULL
)
;

CREATE TABLE Driver_Situacion
(
	ds_code integer NOT NULL,
	return_dateds date NOT NULL,
	current_dateds varchar(50) NOT NULL,
	id_type_sitd integer NULL
)
;

CREATE TABLE "Group"
(
	group_code integer NOT NULL,
	group_contry varchar(50) NOT NULL,
	number_of_tourists integer NOT NULL
)
;

CREATE TABLE Mod_Change
(
	id_mod_change integer NOT NULL,
	id_change_type integer NULL,
	modification_code integer NULL
)
;

CREATE TABLE Modification
(
	modification_code integer NOT NULL,
	modification_date date NOT NULL,
	id_change_type integer NULL,
	solicitude_code integer NULL,
	id_mod_change integer NULL
)
;

CREATE TABLE Programming_Type
(
	id_prog_type integer NOT NULL,
	prog_type_name varchar(50) NOT NULL
)
;

CREATE TABLE Route
(
	route_code integer NOT NULL,
	km_available_start integer NOT NULL,
	km_available_end integer NOT NULL,
	pick_up_location varchar(50) NOT NULL,
	end_time time without time zone NOT NULL
)
;

CREATE TABLE Solicitude
(
	solicitude_code integer NOT NULL,
	programming_start_time time without time zone NOT NULL,
	programming_to_be_done varchar(150) NOT NULL,
	duration_time integer NOT NULL,
	mileage integer NOT NULL,
	car_number varchar(7) NULL,
	id_date date NULL,
	group_code integer NULL,
	route_code integer NULL,
	id_prog_type integer NULL
)
;

CREATE TABLE Type_Car_Situation
(
	id_type_sitc integer NOT NULL,
	type_sitc_name varchar(50) NOT NULL
)
;

CREATE TABLE Type_Driver_Situation
(
	id_type_sitd integer NOT NULL,
	type_sitd_name varchar(50) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Car ADD CONSTRAINT PK_Car
	PRIMARY KEY (car_number)
;

ALTER TABLE Car_Situtuion ADD CONSTRAINT PK_Car_Situtuion
	PRIMARY KEY (cs_code)
;

ALTER TABLE Change_Type ADD CONSTRAINT PK_Change_Type
	PRIMARY KEY (id_change_type)
;

CREATE INDEX IXFK_Change_Type_Mod_Change ON Change_Type (id_mod_change ASC)
;

ALTER TABLE Date ADD CONSTRAINT PK_Date
	PRIMARY KEY (id_date)
;

ALTER TABLE Driver ADD CONSTRAINT PK_Driver
	PRIMARY KEY (dni)
;

CREATE INDEX IXFK_Driver_Car ON Driver (car_number ASC)
;

ALTER TABLE Driver_Situacion ADD CONSTRAINT PK_Driver_Situacion
	PRIMARY KEY (ds_code)
;

ALTER TABLE "Group" ADD CONSTRAINT PK_Group
	PRIMARY KEY (group_code)
;

ALTER TABLE Mod_Change ADD CONSTRAINT PK_Mod_Change
	PRIMARY KEY (id_mod_change)
;

CREATE INDEX IXFK_Mod_Change_Change_Type ON Mod_Change (id_change_type ASC)
;

CREATE INDEX IXFK_Mod_Change_Modification ON Mod_Change (modification_code ASC)
;

ALTER TABLE Modification ADD CONSTRAINT PK_Modification
	PRIMARY KEY (modification_code)
;

CREATE INDEX IXFK_Modification_Change_Type ON Modification (id_change_type ASC)
;

CREATE INDEX IXFK_Modification_Mod_Change ON Modification (id_mod_change ASC)
;

CREATE INDEX IXFK_Modification_Mod_Change_02 ON Modification (id_mod_change ASC)
;

CREATE INDEX IXFK_Modification_Solicitude ON Modification (solicitude_code ASC)
;

ALTER TABLE Programming_Type ADD CONSTRAINT PK_Programming_Type
	PRIMARY KEY (id_prog_type)
;

ALTER TABLE Route ADD CONSTRAINT PK_Route
	PRIMARY KEY (route_code)
;

ALTER TABLE Solicitude ADD CONSTRAINT PK_Solicitude
	PRIMARY KEY (solicitude_code)
;

CREATE INDEX IXFK_Solicitude_Group ON Solicitude (group_code ASC)
;

CREATE INDEX IXFK_Solicitude_Group_02 ON Solicitude (group_code ASC)
;

CREATE INDEX IXFK_Solicitude_Programming_Type ON Solicitude (id_prog_type ASC)
;

CREATE INDEX IXFK_Solicitude_Route ON Solicitude (route_code ASC)
;

ALTER TABLE Type_Car_Situation ADD CONSTRAINT PK_Type_Car_Situation
	PRIMARY KEY (id_type_sitc)
;

ALTER TABLE Type_Driver_Situation ADD CONSTRAINT PK_Type_Driver_Situation
	PRIMARY KEY (id_type_sitd)
;

/* Create Foreign Key Constraints */

ALTER TABLE Car ADD CONSTRAINT FK_Car_Car_Situtuion
	FOREIGN KEY (cs_code) REFERENCES Car_Situtuion (cs_code) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Car_Situtuion ADD CONSTRAINT FK_Car_Situtuion_Type_Car_Situation
	FOREIGN KEY (id_type_sitc) REFERENCES Type_Car_Situation (id_type_sitc) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Driver ADD CONSTRAINT FK_Driver_Car
	FOREIGN KEY (car_number) REFERENCES Car (car_number) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Driver ADD CONSTRAINT FK_Driver_Driver_Situacion
	FOREIGN KEY (ds_code) REFERENCES Driver_Situacion (ds_code) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Driver_Situacion ADD CONSTRAINT FK_Driver_Situacion_Type_Driver_Situation
	FOREIGN KEY (id_type_sitd) REFERENCES Type_Driver_Situation (id_type_sitd) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Mod_Change ADD CONSTRAINT FK_Mod_Change_Change_Type
	FOREIGN KEY (id_change_type) REFERENCES Change_Type (id_change_type) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Mod_Change ADD CONSTRAINT FK_Mod_Change_Modification
	FOREIGN KEY (modification_code) REFERENCES Modification (modification_code) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Modification ADD CONSTRAINT FK_Modification_Solicitude
	FOREIGN KEY (solicitude_code) REFERENCES Solicitude (solicitude_code) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Solicitude ADD CONSTRAINT FK_Solicitude_Car
	FOREIGN KEY (car_number) REFERENCES Car (car_number) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Solicitude ADD CONSTRAINT FK_Solicitude_Date
	FOREIGN KEY (id_date) REFERENCES Date (id_date) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Solicitude ADD CONSTRAINT FK_Solicitude_Group
	FOREIGN KEY (group_code) REFERENCES "Group" (group_code) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Solicitude ADD CONSTRAINT FK_Solicitude_Programming_Type
	FOREIGN KEY (id_prog_type) REFERENCES Programming_Type (id_prog_type) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Solicitude ADD CONSTRAINT FK_Solicitude_Route
	FOREIGN KEY (route_code) REFERENCES Route (route_code) ON DELETE No Action ON UPDATE No Action
;
